### ISSUE TITLE
Allow not specifying plugin version

### ISSUE THREAD

**Issue by vladimir-ikryanov** [TeamDev-IP/JxBrowser-Gradle-Plugin#36]
Right now we have to specify plugin version like that:

```
plugins {
    id("com.teamdev.jxbrowser") version "1.0.2"
}
```

Other plugins such as "java" don't require this:

```
plugins {
    id("java")
}
```

We assume that if we don't specify the version, the latest stable version will be downloaded and used. This is the behavior we would like to have.

But right now, if we don't specify the version, we will get the following error:

```
* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.teamdev.jxbrowser'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:275)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.lambda$resolvePluginRequests$3(DefaultPluginRequestApplicator.java:200)
	at org.gradle.util.internal.CollectionUtils.collect(CollectionUtils.java:212)
	at org.gradle.util.internal.CollectionUtils.collect(CollectionUtils.java:206)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolvePluginRequests(DefaultPluginRequestApplicator.java:198)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolvePluginRequests(DefaultPluginRequestApplicator.java:114)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:103)
	at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:44)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.applyPluginsTo(KotlinScriptEvaluator.kt:220)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.applyPluginsTo(Interpreter.kt:388)
	...
```

In terms of this task we need to find out why we have to specify the plugin version and find out a way to skip the version declaration to force Gradle use the latest version of our plugin.

**Comment by vladimir-ikryanov** [comment]
From https://docs.gradle.org/current/userguide/plugins.html#sec:constrained_syntax:

<img width="1040" alt="image" src="https://github.com/TeamDev-IP/JxBrowser-Gradle-Plugin/assets/6960837/c9ccee97-917a-4326-8186-ae4ff3612daf">

**Comment by vlad-lubenskyi** [comment]
@ivan-diachenko-td this seems to be fix, is it so?

**Comment by ivan-diachenko-td** [comment]
Closing this issue since Gradle does not allow declaring a plugin without setting the version unless it is some core plugin (not our case) or it has been already declared in the Gradle settings file or version catalogs.
